# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
common: &common
  soda_key: <%= ENV["OPENDATA_KEY"] %>

development:
  <<: *common
  secret_key_base: 599534bb2b91983d84d255b7edc62530c15960403becc09e0e03c239e9286c8c20965c1a3de6d839e789ee863783b55865e647c8d72067d93cdd5d1ea4b7eae3

test:
  <<: *common
  secret_key_base: e36f4c3dde026ca75ff3f855850c50ca011ca7490649346270dbe3cf2cc72f0e326d6b0ca21f128424f7b50389794024262895e07864b600a03df883795445bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
